language: python
python:
    - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

branches:
  only:
  - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - jq

env:
    - PLATFORMIO_CI_SRC=examples/VPD.ino
    - PLATFORMIO_CI_SRC=examples/SVP.ino
    - PLATFORMIO_CI_SRC=examples/AVP.ino
    - PLATFORMIO_CI_SRC=examples/RH.ino
    - PLATFORMIO_CI_SRC=examples/FtoC.ino
    - PLATFORMIO_CI_SRC=examples/CtoF.ino

install:
    - pip install -U platformio

script:
  - platformio ci --lib="." --board=uno --board=megaatmega2560 --board=esp12e --board=nodemcu --board=esp32dev
  - jq . library.json
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
